/**
 * dsh-plugin-hub client entry: mounts the Typert Remote, registers
 * dictionaries, and installs the two native integration points —
 *   1. `sidebar.footer.action`  — the store entry button beside Settings
 *      (same geometry as the settings trigger row: 34px wide row / 36px rail);
 *   2. `settings.section`       — a native Settings page (GitHub token, mirror
 *      schedule, sync control) and a shortcut to open the store.
 * The store modal is a portal overlay mounted from the (always-mounted)
 * sidebar entry button, so it floats above the whole Harness UI.
 */
import { createPortal } from 'react-dom';
import { useSyncExternalStore, type ReactNode } from 'react';
import { IconCordisPluginOutline14, Tooltip } from '@deepseek-ai/dsh-client-ui-primitives';
import { TYPERT_REMOTE, makeApi, openStore, openStoreStore, type RemoteApi } from './api';
import { StoreApp } from './StoreApp';
import { StoreSettingsSection } from './settings-section';
import { InsightsUsageView } from './insights';
import storeCss from './store.css';

// Inject the stylesheet once (the same `data-plugin-css` pattern the shell uses).
if (typeof document !== 'undefined' && document.querySelector('style[data-plugin-css="dsh-plugin-hub/store.css"]') === null) {
  const tag = document.createElement('style');
  tag.dataset.plugin = 'dsh-plugin-hub';
  tag.dataset.pluginCss = 'dsh-plugin-hub/store.css';
  tag.textContent = storeCss;
  document.head.appendChild(tag);
}

const NS = 'pluginStore';

const zh = {
  'entry.label': '插件商店',
  'entry.tooltip': '打开插件商店：浏览、搜索、一键安装 DSH 插件',
  'settings.nav': '插件商店',
  'discover.search': '按名称或描述搜索插件…',
  'discover.empty': '没有找到匹配的插件',
  'discover.emptyHint': '提示：首次使用请先前往「设置」页点击「立即同步」，将 GitHub 上的 dsh-plugin 仓库镜像到本地数据库。',
  'settings.open': '打开插件商店',
  // ---- framework copy (0.1.4: follow dsh locale) ----
  'nav.discover': '发现插件',
  'nav.wiki': '百科',
  'nav.skill': 'Skill 商店',
  'nav.installed': '已安装',
  'nav.health': '健康度',
  'nav.publish': '发布',
  // ---- trust ----
  'trust.official': '官方',
  'trust.verified': '认证',
  'trust.community': '社区',
  'trust.unreviewed': '未审核',
  'trust.sourceHint': '信任分层来自社区索引 dsh-hub-index（official/verified/community/unreviewed）',
  'nav.scaffold': '开发脚手架',
  'nav.audit': '审计日志',
  'nav.settings': '设置',
  // ---- issues ----
  'issues.desc': '来自该插件 GitHub 仓库的公开讨论（只读，点击跳转 GitHub 参与讨论）：',
  'issues.openBoard': '打开全部讨论',
  'issues.loading': '加载 GitHub 讨论中…',
  'issues.empty': '该仓库暂无 issue / PR 讨论，或者没有 GitHub 仓库。',
  // ---- health hub ----
  'health.title': '健康度排行榜',
  'health.desc': '按健康指数排序的 Top 20，每日自动更新。点击任意插件查看评分构成与动态图表。',
  'health.updatedAt': '更新于',
  'health.healthy': '健康',
  'health.attention': '需关注',
  'health.stale': '已停滞',
  'health.avg': '平均分',
  'health.loading': '计算健康度中…',
  'health.empty': '暂无插件数据，请先在设置中同步镜像。',
  'health.lastUpdate': '最后更新',
  'health.downloads': '下载',
  'health.openIssues': '开放问题',
  'health.breakdown': '评分构成',
  'health.act': '活跃度',
  'health.dist': '发布渠道',
  'health.bugs': 'Bug 信号',
  'health.comm': '社区规模',
  'health.rel': '版本节奏',
  'health.timeline': '最近动态',
  'health.timelineHint': '时间轴：金色竖线为版本发布节点（顶部标版本号），蓝色折线为 npm 每日真实下载量（无插值）。滚轮缩放、拖拽平移、双击复位。',
  'health.axisDownloads': '下载/日',
  'health.noData': '暂无动态数据',
  'health.noDetail': '暂无健康数据（该插件可能没有 GitHub 仓库）。',
  'health.changeTrend': '更新变动趋势',
  'health.changeTrendHint': '蓝色折线为每日代码提交频次（近 60 天），金色折线为每日加星增量（近 100 条星标）；滚轮缩放、拖拽平移。',
  'health.commitsPerDay': '每日更新频次',
  'health.starsPerDay': '每日加星',
  'health.starsNeedToken': '加星趋势需要 GitHub Token：在「设置」页配置令牌后即可显示每日加星增量（未配置时不展示）。',
  // ---- update ----
  'action.update': '更新',
  'action.updating': '更新中…',
  'installed.updateTitle': '有新版本可用',
  // ---- scaffold ----
  'scaffold.title': '插件开发脚手架',
  'scaffold.desc': '想给生态添砖加瓦？按以下步骤创建 DSH 插件，本地安装后打开商店「发布」页，一键发布到 GitHub / npm —— 安全扫描通过即上线，全生态可搜索安装。',
  'scaffold.step1.title': '了解插件结构',
  'scaffold.step1.before': '一个 DSH 插件就是一个 npm 包：package.json 中声明 ',
  'scaffold.step1.mid': '（host 端 Cordis 层）与 ',
  'scaffold.step1.after': '（浏览器端 UI 包）。可参考已上架的 ',
  'scaffold.step1.sameAs': '（本商店即采用相同结构）以及 ',
  'scaffold.step1.docs': 'DeepSeek Harness 官方文档',
  'scaffold.step1.tail': '。',
  'scaffold.step2.title': '创建工程',
  'scaffold.step2.text': '克隆模板或从零初始化，实现功能后本地调试：',
  'scaffold.step3.title': '发布上线',
  'scaffold.step3.text': '用 dsh plugin add 本地安装（自动归入「自创作插件」），然后打开商店「发布」页：输入 GitHub / npm 令牌 → 选择插件 → 填 Markdown 图文介绍 → 选公开/私人 + 标签 → 一键发布。发布前经过安全扫描（高风险自动驳回），公开即上线，无需手动打 Topic。',
  'scaffold.step3.cats': '可用的分类标签：',
  'scaffold.step3.catsHint': '（根据 package.json keywords 与仓库 Topics 自动归类）',
  'scaffold.copy': '复制',
  'scaffold.copyAria': '复制命令',
  'scaffold.linkRepo': '官方仓库',
  'scaffold.linkDocs': '开发文档',
  'scaffold.linkEco': '浏览生态仓库',
  // ---- detail tabs ----
  'detail.tab.overview': '概览',
  'detail.tab.usage': '使用说明',
  'detail.tab.versions': '版本历史',
  'detail.tab.graph': '依赖拓扑',
  'detail.tab.reviews': '评价',
  'detail.tab.issues': 'GitHub 讨论',
  'detail.tab.health': '健康度',
  'detail.tab.wiki': '百科',
  'detail.tab.bench': '跑分',
  // ---- bench (dsh-bench 独立项目产出) ----
  'bench.loading': '加载跑分…',
  'bench.runNow': '立即跑分',
  'bench.running': '跑分中…',
  'bench.runHint': '（Mock 零 token / 端到端消耗 token）',
  'bench.e2e': '端到端跑分',
  'bench.e2eRunning': '端到端跑分中…',
  'bench.e2eConfirm': '端到端跑分将消耗你的 token（真实调用模型）。不保证测试不会死循环 / 无法预知具体消耗；超时 120s 自动中止。确定继续？',
  'bench.noEntry': '暂无该插件的跑分数据',
  'bench.hint': '跑分由独立项目 dsh-bench 产出（虚拟 DSH 环境 L1 加载基准，零 token）；运行 dsh-bench 后将报告放到本机即可看到',
  'bench.score': '综合性能分',
  'bench.updated': '跑分时间',
  'bench.ecoAvg': '生态均值',
  'bench.failed': '加载失败',
  'bench.metrics': '各环节耗时',
  'bench.wall': '启动总耗时',
  'bench.apply': '插件加载',
  'bench.bundle': 'bundle(gzip)',
  'bench.hooks': 'hook 数',
  'bench.note': '跑分 = 动态实测（dsh-bench），健康度 = 静态状态；两者互补。分值为批内相对分，跨机可比需同机基线。',
  // ---- wiki ----
  'wiki.title': '插件百科库',
  'wiki.desc': '不知道某个插件能干什么、怎么用、最佳实践是什么？在这里查——覆盖商店同步插件与 Blue-Whale 目录收录的 1800+ 仓库。',
  'wiki.search': '搜索插件…',
  'wiki.allCat': '全部分类',
  'wiki.allSource': '全部来源',
  'wiki.srcMirror': '商店同步',
  'wiki.srcCatalog': '目录收录',
  'wiki.srcCatalogHint': '来自 Blue-Whale-Harness 社区目录（1812 仓库），仅索引未同步详情',
  'wiki.catalogNoDesc': '来自社区目录 Blue-Whale-Harness，点击查看 GitHub',
  'wiki.loading': '加载百科中…',
  'wiki.empty': '没有匹配的百科条目',
  'wiki.total': '共',
  'wiki.noEntry': '暂无百科内容',
  'wiki.install': '安装方式',
  'wiki.installHint': '（在详情页顶部点「安装」即可，这里只是命令备查）',
  'wiki.what': '它是什么',
  'wiki.highlights': '它能干什么 / 价值在哪',
  'wiki.howto': '怎么用',
  'wiki.bestPractices': '最佳实践 / 注意事项',
  'wiki.related': '相关插件',
  'wiki.latestVer': '最新版本',
  'wiki.verCount': '版本',
  'wiki.deps': '依赖',
  'wiki.homepage': '主页',
  // ---- skill store ----
  'skill.title': 'Skill 商店',
  'skill.desc': '对话中可调用的技能（SKILL.md）：浏览全生态技能（SKILL.md 是通用格式，所有平台的技能都可用）→ 一键安装到本机 → 对话时告诉 AI「用 xx 技能」即可调用。',
  'skill.install': '安装',
  'skill.uninstall': '卸载',
  'skill.installed': '已安装',
  'skill.back': '返回列表',
  'skill.searchPlaceholder': '搜索技能名称 / 描述 / 作者…',
  'skill.total': '共',
  'skill.loading': '加载中…',
  'skill.empty': '还没有技能，试试先「立即同步」',
  'skill.emptyHint': '同步会从 GitHub 各 skill 主题收集全生态技能',
  'skill.howToUse': '安装后如何调用：重启 dsh，然后在对话中对 AI 说：',
  'skill.howToUseCmd': '使用 xxx 技能 / use the xxx skill',
  'skill.source': '来源:',
  'skill.path': '路径:',
  'skill.content': '技能内容（SKILL.md）',
  'skill.platformAll': '全平台',
  'skill.platformDsh': 'DSH 专用',
  'skill.platformGeneral': '通用',
  // ---- publish view ----
  'publish.title': '一键发布插件',
  'publish.desc': '把本地开发好的插件一键发布到 GitHub 仓库和/或 npm，公开即上线，全世界的 DSH 用户都能通过本商店搜索并安装。',
  'publish.stepTarget': '1. 发布目标',
  'publish.target.github': 'GitHub 发布',
  'publish.target.npm': 'npm 发布',
  'publish.target.both': '两者都要',
  'publish.stepKeys': '2. API Key',
  'publish.ghTokenPlaceholder': 'GitHub 个人访问令牌（需勾选 repo 写入权限，ghp_…）',
  'publish.npmTokenPlaceholder': 'npm 访问令牌（Automation 类型，npm_…）',
  'publish.keysHint': '出于安全考虑，令牌仅本次发布使用、绝不保存；每次发布都需要重新输入。',
  'publish.stepPlugin': '3. 选择要发布的插件',
  'publish.loading': '加载中…',
  'publish.noOwn': '还没有可发布的插件。请先在「开发脚手架」中创建插件并用 dsh plugin add 本地安装，它会出现在「自创作插件」分类。',
  'publish.stepInfo': '4. 发布信息',
  'publish.mdEdit': '编辑',
  'publish.mdPreview': '预览',
  'publish.mdEmpty': '*（空白——预览为空）*',
  'publish.mdHint': '支持 Markdown 图文：标题、列表、加粗、代码、图片（![说明](图片链接)）等。',
  'publish.writeReadme': '将介绍写入仓库 README.md（仅当插件目录没有 README 时生成，不会覆盖原文档）',
  'publish.descPlaceholder': '插件介绍（支持 Markdown 图文，将作为仓库描述与 Release 说明；可长可短）',
  'publish.visibility': '可见性：',
  'publish.public': '公开',
  'publish.private': '私人',
  'publish.visibilityHint': '仅 GitHub 仓库可见性；npm 发布固定公开',
  'publish.topics': '标签：',
  'publish.submit': '🚀 一键发布',
  'publish.publishing': '发布中…',
  'publish.starting': '启动发布…',
  'publish.errNoPlugin': '请先选择一个要发布的插件',
  'publish.published': '已发布',
  'publish.secWarningTitle': '⚠️ 发布成功，但安全扫描发现以下可疑项（请自行确认无风险后再公开推广）：',
  'app.title': '插件商店',
  'app.detail': '插件详情',
  'app.close': '关闭',
  'action.install': '安装',
  'action.uninstall': '卸载',
  'action.enable': '启用',
  'action.disable': '禁用',
  'action.installing': '安装中…',
  // ---- env hint ----
  'install.envHintTitle': '该插件在运行时会读取以下环境变量（请按需配置，否则部分功能可能不可用）：',
  'install.envHintDesc': '可参考插件 README 或源码确认用途；配置后重启 DSH 生效。',
  'err.dismiss': '知道了',
  'action.uninstalling': '卸载中…',
  'action.processing': '处理中…',
  'action.retry': '重试',
  'state.installed': '已安装',
  'state.disabled': '已禁用',
  'state.installing': '安装中',
  'category.tool': '工具',
  'category.agent': 'Agent',
  'category.ui': '界面美化',
  'category.data': '数据处理',
  'category.vision': '视觉多模态',
  'category.docs': '文档办公',
  'category.memory': '记忆知识',
  'category.usage': '模型用量',
  'category.notify': '通知通讯',
  'category.dev': '开发编码',
  'category.chat': '对话会话',
  'category.hub': '聚合资源',
  'category.hubExt': '可扩展类',
  'category.other': '其他',
  'category.all': '全部',
  'source.npm': 'npm 直装',
  'source.github': 'GitHub 源码',
  'btn.npmInstall': 'npm 安装',
  'btn.githubInstall': 'GitHub 安装',
  'err.detail.toggle': '查看详情',
  'err.detail.collapse': '收起详情',
  'empty.usage': '还没有用量数据',
  'empty.usageHint': '发送第一条消息后，这里会展示每个请求的 token 与缓存命中率。',
  'usage.input': '输入',
  'usage.output': '输出',
  'usage.hitRate': '缓存命中率',
  'usage.totalInput': '总输入',
  'usage.totalOutput': '总输出',
  'usage.estimatedCost': '估算费用',
  'usage.modelMix': '模型分布',
  'usage.chartHint': '滚轮缩放 · 拖动平移 · 双击复位',
  'usage.tab': '用量',
  'sort.random': '随机推荐（防刷榜）',
  'sort.health': '按健康度',
  'sort.stars': '按 Star 数',
  'sort.rating': '按评分',
  'sort.downloads': '按下载量',
  'sort.updated': '按最近更新',
  'sort.name': '按名称',
  'filter.installedOnly': '仅看已安装',
  'downloads.title': 'npm 上月真实下载量（未发布则无）',
  'downloads.unknown': 'npm 未查询到',
  // ---- installed view ----
  'installed.title': '已安装插件',
  'installed.system': '系统插件',
  'installed.ui': '界面增强',
  'installed.download': '下载插件',
  'installed.own': '自创作插件',
  'installed.core': '核心服务',
  'installed.protected': '受保护',
  'installed.unmanaged': '未托管',
  'installed.managed': '已托管',
  'installed.partialEnable': '部分启用',
  'installed.allEnable': '全部启用',
  'installed.coreDesc': 'DSH 运行的基础组件与界面能力（受保护项不可禁用）',
  'installed.items': '项',
  'installed.downloadDesc': '通过插件商店安装的第三方插件',
  'installed.ownDesc': '本地开发或改造的插件（file:/link: 安装，源码在本机；发布状态以徽章区分）',
  'installed.group.core': '核心服务',
  'installed.group.ui': '界面增强',
  'installed.group.tool': '开发工具',
  'installed.group.llm': '模型与 LLM',
  'installed.group.agent': 'Agent',
  'installed.group.workflow': '工作流',
  'installed.group.data': '数据处理',
  'installed.group.notification': '通知',
  'installed.group.other': '其他',
  'installed.group.hubExt': '可扩展类',
  // ---- settings view ----
  'settings.title': '插件商店设置',
  'settings.operator': '操作者身份（审计日志用）',
  'settings.operatorHint': '安装、卸载、启用、禁用、评分等操作会以该名称记录到审计日志，满足企业合规追溯要求。',
  'settings.anonymous': 'anonymous（未设置显示名）',
  'settings.saveActor': '保存显示名',
  'settings.githubToken': 'GitHub 私人 Token',
  'settings.githubTokenHint': 'GitHub API 匿名受限（10 次/分钟、核心 60 次/小时）。配置私人 Token（ghp-...，需 public_repo 仓库读取权限）后，搜索限频提升至 30 次/分钟、核心 5000 次/小时，镜像同步可完整拉取全部仓库的版本历史。Token 仅保存在本机数据库，不会发送到任何第三方。',
  'settings.tokenPlaceholder': '粘贴 GitHub 私人 Token',
  'settings.saveToken': '保存 Token',
  'settings.mirror': '镜像同步（本地数据库缓存）',
  'settings.mirrorHint': '定期将 GitHub 上标记 topic:dsh-plugin（或在仓库描述中标注 #dsh-plugin）的仓库元数据缓存到本地数据库，商店搜索与加载不再受网络与限频影响。自动同步在后台执行，不阻塞界面。',
  // ---- connector (dsh-connector 官方可扩展类插件) ----
  'connector.title': '连接器（IM 桥接）',
  'connector.desc': '官方可扩展类插件 dsh-connector：把飞书/企微/钉钉/QQ 等 IM 消息接入 dsh 会话，对话中直接收发 IM 消息。配置保存后重启 dsh 生效。',
  'connector.notInstalled': 'dsh-connector 未安装。请在终端执行：dsh plugin --profile web add E:/DeepSeek Harness/work/dsh-connector',
  'connector.save': '保存配置',
  'connector.refresh': '刷新状态',
  'connector.restartHint': '保存后重启 dsh 生效；事件订阅 URL 配为 http://<本机>:端口/feishu/event（飞书开放平台 → 事件订阅）。',
  'settings.syncInterval': '自动同步间隔（小时，0=关闭）',
  'settings.savePlan': '保存计划',
  'settings.syncNow': '立即同步',
  'settings.idle': '空闲',
  'settings.lastSync': '上次同步',
  'settings.nextPlan': '下次计划',
  'settings.plugins': '个仓库',
  'settings.dbPath': '数据库路径',
  'settings.uncached': '未查询',
  'settings.clearToken': '清除 Token',
  'settings.tokenSaved': 'Token 已保存',
  'settings.tokenCleared': 'Token 已清除',
  'settings.planSaved': '同步计划已保存',
  // ---- audit view ----
  'audit.title': '操作审计日志',
  'audit.allActions': '全部操作',
  'audit.byActor': '按操作者筛选',
  'audit.byTarget': '按对象筛选',
  'audit.time': '时间',
  'audit.actor': '操作者',
  'audit.action': '操作',
  'audit.target': '对象',
  'audit.result': '结果',
  'audit.detail': '详情',
  'audit.ok': '成功',
  'audit.failed': '失败',
  'audit.uninstall': '卸载',
  'audit.install': '安装',
  'audit.enable': '启用',
  'audit.disable': '禁用',
  'audit.rate': '评分',
  'audit.tokenSet': '设置 Token',
  'audit.tokenClear': '清除 Token',
  'audit.sync': '镜像同步',
  'audit.scheduleSet': '同步计划',
};

const en: Record<keyof typeof zh, string> = {
  'entry.label': 'Plugin Store',
  'entry.tooltip': 'Open the plugin store: browse, search and one-click install DSH plugins',
  'settings.nav': 'Plugin Store',
  // ---- update ----
  'action.update': 'Update',
  'action.updating': 'Updating…',
  'installed.updateTitle': 'A newer version is available',
  'issues.desc': 'Public discussions from this plugin\'s GitHub repo (read-only — click through to GitHub to join in):',
  'issues.openBoard': 'Open all discussions',
  'issues.loading': 'Loading GitHub discussions…',
  'issues.empty': 'No issues / PRs yet, or this plugin has no GitHub repo.',
  // ---- health hub ----
  'health.title': 'Health Leaderboard',
  'health.desc': 'Top 20 by health score, refreshed daily. Click any plugin for the breakdown and activity charts.',
  'health.updatedAt': 'Updated',
  'health.healthy': 'Healthy',
  'health.attention': 'Attention',
  'health.stale': 'Stale',
  'health.avg': 'Average',
  'health.loading': 'Scoring plugins…',
  'health.empty': 'No plugin data yet — sync the mirror in Settings first.',
  'health.lastUpdate': 'Last update',
  'health.downloads': 'Downloads',
  'health.openIssues': 'Open issues',
  'health.breakdown': 'Score breakdown',
  'health.act': 'Activity',
  'health.dist': 'Distribution',
  'health.bugs': 'Bug signal',
  'health.comm': 'Community',
  'health.rel': 'Release cadence',
  'health.timeline': 'Recent activity',
  'health.timelineHint': 'Gold bars are release markers (version on top); the blue line is real daily npm downloads (no interpolation). Wheel to zoom, drag to pan.',
  'health.axisDownloads': 'dl/day',
  'health.noData': 'No activity data yet',
  'health.noDetail': 'No health data (this plugin may have no GitHub repo).',
  'health.changeTrend': 'Change trend',
  'health.changeTrendHint': 'Blue: daily commits (60 days). Gold: daily star gains (last 100 stars). Wheel to zoom, drag to pan.',
  'health.commitsPerDay': 'Commits / day',
  'health.starsPerDay': 'Stars / day',
  'health.starsNeedToken': 'Star trend needs a GitHub token: configure one in Settings to see daily star gains (hidden when not configured).',
  // ---- scaffold ----
  'scaffold.title': 'Plugin Scaffold',
  'scaffold.desc': 'Want to contribute? Create a DSH plugin, install it locally, then open the store "Publish" page and ship it to GitHub / npm in one click — public once the security scan passes.',
  'scaffold.step1.title': 'Understand the plugin shape',
  'scaffold.step1.before': 'A DSH plugin is an npm package: package.json declares ',
  'scaffold.step1.mid': ' (host-side Cordis layer) and ',
  'scaffold.step1.after': ' (browser UI bundle). See the published ',
  'scaffold.step1.sameAs': ' (this store uses the same structure), plus the ',
  'scaffold.step1.docs': 'DeepSeek Harness docs',
  'scaffold.step1.tail': '.',
  'scaffold.step2.title': 'Create the project',
  'scaffold.step2.text': 'Clone a template or init from scratch, then debug locally:',
  'scaffold.step3.title': 'Publish & go live',
  'scaffold.step3.text': 'Install locally with dsh plugin add (auto-listed under "My plugins"), then open the store "Publish" page: enter GitHub / npm tokens → pick the plugin → write a Markdown description → choose public/private + topics → publish. A security scan runs first (high-risk is auto-rejected) — public means live, no manual topic needed.',
  'scaffold.step3.cats': 'Available categories: ',
  'scaffold.step3.catsHint': '(auto-derived from package.json keywords and repo topics)',
  'scaffold.copy': 'Copy',
  'scaffold.copyAria': 'Copy command',
  'scaffold.linkRepo': 'Official repo',
  'scaffold.linkDocs': 'Docs',
  'scaffold.linkEco': 'Browse ecosystem',
  // ---- detail tabs ----
  'detail.tab.overview': 'Overview',
  'detail.tab.usage': 'Usage',
  'detail.tab.versions': 'Versions',
  'detail.tab.graph': 'Dependency graph',
  'detail.tab.reviews': 'Reviews',
  'detail.tab.issues': 'GitHub discussions',
  'detail.tab.health': 'Health',
  'detail.tab.wiki': 'Wiki',
  'detail.tab.bench': 'Bench',
  // ---- bench (from the standalone dsh-bench project) ----
  'bench.loading': 'Loading bench…',
  'bench.runNow': 'Run bench now',
  'bench.running': 'Benchmarking…',
  'bench.runHint': '(Mock zero-token / E2E uses your tokens)',
  'bench.e2e': 'E2E bench',
  'bench.e2eRunning': 'E2E benchmarking…',
  'bench.e2eConfirm': 'E2E bench will consume your tokens (real model calls). It is not guaranteed to avoid infinite loops / exact cost is unknown; auto-abort after 120s. Continue?',
  'bench.noEntry': 'No bench data for this plugin yet',
  'bench.hint': 'Bench is produced by the standalone dsh-bench project (virtual DSH L1 load bench, zero token); place its report locally to see scores here',
  'bench.score': 'Performance score',
  'bench.updated': 'Bench time',
  'bench.ecoAvg': 'Ecosystem avg',
  'bench.failed': 'Load failed',
  'bench.metrics': 'Stage timings',
  'bench.wall': 'Boot wall',
  'bench.apply': 'Plugin load',
  'bench.bundle': 'Bundle (gzip)',
  'bench.hooks': 'Hooks',
  'bench.note': 'Bench = dynamic measurement (dsh-bench); health = static state; they complement each other. Scores are batch-relative; cross-machine comparison needs the same-machine baseline.',
  // ---- wiki ----
  'wiki.title': 'Plugin Wiki',
  'wiki.desc': 'What does a plugin do? How to use it? Best practices? Look it up here — covers mirrored plugins plus 1800+ repos from the Blue-Whale catalog.',
  'wiki.search': 'Search plugins…',
  'wiki.allCat': 'All categories',
  'wiki.allSource': 'All sources',
  'wiki.srcMirror': 'Mirrored',
  'wiki.srcCatalog': 'Catalog',
  'wiki.srcCatalogHint': 'From the Blue-Whale-Harness community catalog (1812 repos), index-only without details',
  'wiki.catalogNoDesc': 'From the Blue-Whale-Harness community catalog — open GitHub for details',
  'wiki.loading': 'Loading wiki…',
  'wiki.empty': 'No matching entries',
  'wiki.total': 'Total',
  'wiki.noEntry': 'No wiki content yet',
  'wiki.install': 'Install (optional)',
  'wiki.installHint': '(hit Install at the top of the detail page — commands here are for reference)',
  'wiki.what': 'What it is',
  'wiki.highlights': 'What it does / why it matters',
  'wiki.howto': 'How to use',
  'wiki.bestPractices': 'Best practices / notes',
  'wiki.related': 'Related plugins',
  'wiki.latestVer': 'Latest',
  'wiki.verCount': 'Versions',
  'wiki.deps': 'Deps',
  'wiki.homepage': 'Homepage',
  // ---- skill store ----
  'skill.title': 'Skill Store',
  'skill.desc': 'Conversation-callable skills (SKILL.md): browse the whole ecosystem (SKILL.md is a universal format — skills from any platform work in dsh) → one-click install → then tell the AI "use the xx skill" in chat.',
  'skill.install': 'Install',
  'skill.uninstall': 'Uninstall',
  'skill.installed': 'Installed',
  'skill.back': 'Back to list',
  'skill.searchPlaceholder': 'Search skills by name / description / author…',
  'skill.total': 'Total',
  'skill.loading': 'Loading…',
  'skill.empty': 'No skills yet — try "Sync now" first',
  'skill.emptyHint': 'Sync collects skills from GitHub skill topics',
  'skill.howToUse': 'After install, restart dsh and tell the AI in chat:',
  'skill.howToUseCmd': 'use the xxx skill',
  'skill.source': 'Source:',
  'skill.path': 'Path:',
  'skill.content': 'Skill content (SKILL.md)',
  'skill.platformAll': 'All platforms',
  'skill.platformDsh': 'DSH-native',
  'skill.platformGeneral': 'General',
  'discover.search': 'Search plugins by name or description…',
  'discover.empty': 'No plugins match your query',
  'discover.emptyHint': 'Tip: on first use, open Settings and click “Sync now” to mirror GitHub dsh-plugin repositories into the local database.',
  'settings.open': 'Open plugin store',
  // ---- framework copy ----
  'nav.discover': 'Discover',
  'nav.wiki': 'Wiki',
  'nav.skill': 'Skills',
  'nav.installed': 'Installed',
  'nav.health': 'Health',
  'nav.publish': 'Publish',
  // ---- trust ----
  'trust.official': 'Official',
  'trust.verified': 'Verified',
  'trust.community': 'Community',
  'trust.unreviewed': 'Unreviewed',
  'trust.sourceHint': 'Trust level from the dsh-hub-index community index (official/verified/community/unreviewed)',
  'nav.scaffold': 'Scaffold',
  'nav.audit': 'Audit',
  'nav.settings': 'Settings',
  // ---- publish view ----
  'publish.title': 'One-click Publish',
  'publish.desc': 'Publish your locally-developed plugin to GitHub and/or npm in one click. Public = live: every DSH user worldwide can find and install it from this store.',
  'publish.stepTarget': '1. Target',
  'publish.target.github': 'GitHub',
  'publish.target.npm': 'npm',
  'publish.target.both': 'Both',
  'publish.stepKeys': '2. API Key',
  'publish.ghTokenPlaceholder': 'GitHub personal access token (needs repo write scope, ghp_…)',
  'publish.npmTokenPlaceholder': 'npm access token (Automation type, npm_…)',
  'publish.keysHint': 'For security, tokens are used for this publish only and are never stored — re-enter them every time.',
  'publish.stepPlugin': '3. Pick your plugin',
  'publish.loading': 'Loading…',
  'publish.noOwn': 'No publishable plugins yet. Create one under “Scaffold” and install it locally with dsh plugin add — it will show up here.',
  'publish.stepInfo': '4. Publish info',
  'publish.mdEdit': 'Edit',
  'publish.mdPreview': 'Preview',
  'publish.mdEmpty': '*（empty — nothing to preview）*',
  'publish.mdHint': 'Markdown with images supported: headings, lists, bold, code, images (![alt](image-url)).',
  'publish.writeReadme': 'Write this description into the repo README.md (only generated when the plugin has no README; existing docs are never overwritten)',
  'publish.descPlaceholder': 'Plugin description (Markdown with images supported; becomes the repo description & release notes)',
  'publish.visibility': 'Visibility:',
  'publish.public': 'Public',
  'publish.private': 'Private',
  'publish.visibilityHint': 'GitHub repo visibility only; npm publishing is always public',
  'publish.topics': 'Topics:',
  'publish.submit': '🚀 Publish',
  'publish.publishing': 'Publishing…',
  'publish.starting': 'Starting…',
  'publish.errNoPlugin': 'Pick a plugin to publish first',
  'publish.published': 'published',
  'publish.secWarningTitle': '⚠️ Published, but the security scan flagged the following (verify they are safe before promoting):',
  'app.title': 'Plugin Store',
  'app.detail': 'Plugin Detail',
  'app.close': 'Close',
  'action.install': 'Install',
  'action.uninstall': 'Uninstall',
  'action.enable': 'Enable',
  'action.disable': 'Disable',
  'action.installing': 'Installing…',
  // ---- env hint ----
  'install.envHintTitle': 'This plugin reads these environment variables at runtime (configure them if needed, or some features may not work):',
  'install.envHintDesc': 'See the plugin README / source for details; restart DSH after configuring.',
  'err.dismiss': 'Got it',
  'action.uninstalling': 'Uninstalling…',
  'action.processing': 'Processing…',
  'action.retry': 'Retry',
  'state.installed': 'Installed',
  'state.disabled': 'Disabled',
  'state.installing': 'Installing',
  'category.tool': 'Tools',
  'category.agent': 'Agent',
  'category.ui': 'UI & Themes',
  'category.data': 'Data',
  'category.vision': 'Vision & Media',
  'category.docs': 'Docs & Office',
  'category.memory': 'Memory & Knowledge',
  'category.usage': 'Usage & Cost',
  'category.notify': 'Notify & Messaging',
  'category.dev': 'Dev & Coding',
  'category.chat': 'Chat & Session',
  'category.hub': 'Hub & Registry',
  'category.hubExt': 'Hub Extensions',
  'category.other': 'Other',
  'category.all': 'All',
  'source.npm': 'npm',
  'source.github': 'GitHub',
  'btn.npmInstall': 'Install via npm',
  'btn.githubInstall': 'Install via GitHub',
  'err.detail.toggle': 'Details',
  'err.detail.collapse': 'Collapse',
  'empty.usage': 'No usage data yet',
  'empty.usageHint': 'Send a message to see per-request tokens and cache hit rate here.',
  'usage.input': 'Input',
  'usage.output': 'Output',
  'usage.hitRate': 'Cache hit rate',
  'usage.totalInput': 'Total input',
  'usage.totalOutput': 'Total output',
  'usage.estimatedCost': 'Est. cost',
  'usage.modelMix': 'Model mix',
  'usage.chartHint': 'Wheel to zoom · drag to pan · double-click to reset',
  'usage.tab': 'Usage',
  'sort.random': 'Random (anti-gaming)',
  'sort.health': 'Health',
  'sort.stars': 'Stars',
  'sort.rating': 'Rating',
  'sort.downloads': 'Downloads',
  'sort.updated': 'Recently updated',
  'sort.name': 'Name',
  'filter.installedOnly': 'Installed only',
  'downloads.title': 'Real npm monthly downloads (none if unpublished)',
  'downloads.unknown': 'npm n/a',
  // ---- installed view ----
  'installed.title': 'Installed plugins',
  'installed.system': 'System plugins',
  'installed.ui': 'UI extensions',
  'installed.download': 'Downloaded plugins',
  'installed.own': 'Self-made plugins',
  'installed.core': 'Core',
  'installed.protected': 'Protected',
  'installed.unmanaged': 'Unmanaged',
  'installed.managed': 'Managed',
  'installed.partialEnable': 'Partial',
  'installed.allEnable': 'Enable all',
  'installed.coreDesc': 'DSH foundation components and UI capabilities (protected items cannot be disabled)',
  'installed.items': 'items',
  'installed.downloadDesc': 'Third-party plugins installed via the store',
  'installed.ownDesc': 'Self-developed or modified plugins (file:/link: install; source on this machine; publish state via badge)',
  'installed.group.core': 'Core',
  'installed.group.ui': 'UI',
  'installed.group.tool': 'Tools',
  'installed.group.llm': 'Models & LLM',
  'installed.group.agent': 'Agent',
  'installed.group.workflow': 'Workflow',
  'installed.group.data': 'Data',
  'installed.group.notification': 'Notifications',
  'installed.group.other': 'Other',
  'installed.group.hubExt': 'Hub Extensions',
  // ---- settings view ----
  'settings.title': 'Plugin Store Settings',
  'settings.operator': 'Operator identity (used in audit log)',
  'settings.operatorHint': 'Install, uninstall, enable, disable, rate and other actions are recorded under this name in the audit log to meet enterprise compliance traceability.',
  'settings.anonymous': 'anonymous (no display name set)',
  'settings.saveActor': 'Save name',
  'settings.githubToken': 'GitHub personal token',
  'settings.githubTokenHint': 'GitHub API anonymous is rate-limited (10/min, core 60/hr). Configure a personal token (ghp-... with public_repo read scope) to raise the limits to 30/min and 5000/hr, and mirror sync can pull the full version history of every repository. The token is stored only in your local database and never sent to any third party.',
  'settings.tokenPlaceholder': 'Paste GitHub personal token',
  'settings.saveToken': 'Save token',
  'settings.mirror': 'Mirror sync (local database cache)',
  'settings.mirrorHint': 'Periodically cache the metadata of GitHub repositories tagged topic:dsh-plugin (or marked #dsh-plugin in description) to the local database, so store search and loading are no longer affected by network and rate limits. Auto sync runs in the background without blocking the UI.',
  // ---- connector (official hub-ext plugin dsh-connector) ----
  'connector.title': 'Connectors (IM bridge)',
  'connector.desc': 'Official hub-ext plugin dsh-connector: bridge Feishu/WeCom/DingTalk/QQ IM messages into dsh sessions and send messages back from conversations. Restart dsh after saving.',
  'connector.notInstalled': 'dsh-connector is not installed. Run: dsh plugin --profile web add E:/DeepSeek Harness/work/dsh-connector',
  'connector.save': 'Save config',
  'connector.refresh': 'Refresh',
  'connector.restartHint': 'Restart dsh to apply; set event subscription URL to http://<host>:<port>/feishu/event (Feishu open platform → event subscription).',
  'settings.syncInterval': 'Auto sync interval (hours, 0=disable)',
  'settings.savePlan': 'Save plan',
  'settings.syncNow': 'Sync now',
  'settings.idle': 'idle',
  'settings.lastSync': 'Last sync',
  'settings.nextPlan': 'Next plan',
  'settings.plugins': 'repositories',
  'settings.dbPath': 'Database path',
  'settings.uncached': 'Not queried',
  'settings.clearToken': 'Clear token',
  'settings.tokenSaved': 'Token saved',
  'settings.tokenCleared': 'Token cleared',
  'settings.planSaved': 'Sync plan saved',
  // ---- audit view ----
  'audit.title': 'Audit log',
  'audit.allActions': 'All actions',
  'audit.byActor': 'Filter by actor',
  'audit.byTarget': 'Filter by target',
  'audit.time': 'Time',
  'audit.actor': 'Actor',
  'audit.action': 'Action',
  'audit.target': 'Target',
  'audit.result': 'Result',
  'audit.detail': 'Detail',
  'audit.ok': 'Success',
  'audit.failed': 'Failed',
  'audit.uninstall': 'Uninstall',
  'audit.install': 'Install',
  'audit.enable': 'Enable',
  'audit.disable': 'Disable',
  'audit.rate': 'Rate',
  'audit.tokenSet': 'Set token',
  'audit.tokenClear': 'Clear token',
  'audit.sync': 'Mirror sync',
  'audit.scheduleSet': 'Sync plan',
};

export const inject = ['slots', 'locale', 'remote'];

function useOpenStore(): boolean {
  return useSyncExternalStore(openStoreStore.subscribe, openStoreStore.getSnapshot, openStoreStore.getSnapshot);
}

/** The sidebar footer entry button: same size as the regular function buttons.
 * Also hosts the store modal portal so it can be opened from anywhere. */
function StoreEntryButton({ wide, api, t }: { wide: boolean; api: RemoteApi; t: (k: string) => string }): ReactNode {
  const open = useOpenStore();
  const button = (
    <button
      type="button"
      className={`dps-entry${wide ? '' : ' dps-entry-rail'}`}
      aria-label={t('entry.label')}
      onClick={openStore}
    >
      <IconCordisPluginOutline14 size={wide ? 14 : 18} />
      {wide && <span className="dps-entry-label">{t('entry.label')}</span>}
    </button>
  );
  return (
    <>
      {wide ? button : <Tooltip label={t('entry.label')} delayMs={500}>{button}</Tooltip>}
      {open && createPortal(<StoreApp api={api} t={t} />, document.body)}
    </>
  );
}

/**
 * Mount the Remote contribution and register the native integration points.
 */
export async function apply(ctx: any): Promise<() => Promise<void>> {
  const disposeRemote = await ctx.remote.$mount(TYPERT_REMOTE);
  const disposeLocale = ctx.locale.register(NS, { zh, en });

  const feature = ctx.inject(['remote.pluginStore'], (scope: any) => {
    const api: RemoteApi = makeApi(scope.remote);
    const t = ctx.locale.bind(NS);

    // 1. Main-interface entry button (sidebar foot, beside Settings).
    scope.slots.inject('sidebar.footer.action', () => scope.slots.register({
      name: 'sidebar.footer.action',
      id: 'plugin-store',
      order: 10,
      label: () => t('entry.label'),
      locale: NS,
      inject: () => ({ api, t }),
    }, StoreEntryButton));

    // 2. Native settings section (token + mirror + open store).
    scope.slots.inject('settings.section', () => scope.slots.register({
      name: 'settings.section',
      id: 'plugin-store',
      order: 20,
      label: () => zh['settings.nav'],
      locale: NS,
      inject: () => ({ api, openStore }),
    }, StoreSettingsSection));

    // 3. 0.1.3 insights: 用量视图 tab — registered into the conversation
    //    view ring (list kind, sits beside 对话/轨迹 tabs). NOT the details
    //    column: details is a single-kind slot already owned by the stock
    //    DetailsPanel, and a second injection there breaks the whole plugin.
    scope.slots.inject('conversation.view', () => scope.slots.register({
      name: 'conversation.view',
      id: 'plugin-store-usage',
      order: 15,
      locale: NS,
      label: () => t('usage.tab'),
      inject: (sessionId: string) => ({ sessionId, t }),
    }, InsightsUsageView));

    return () => {};
  });

  return async () => {
    await feature.dispose();
    disposeLocale();
    await disposeRemote();
  };
}

export default { apply, inject };
